devices([
  "iPhone 17 Pro Max",
  "iPhone 17",
])

languages(["en-GB"])

scheme("flixr")
test_target_name("flixrUITests")
xcargs("-skip-testing:flixrTests -skip-testing:flixrUITests/flixrUITests/testExample -skip-testing:flixrUITests/flixrUITests/testLaunchPerformance -skip-testing:flixrUITests/flixrUITestsLaunchTests/testLaunch")
derived_data_path("/Users/andrewking/Library/Developer/Xcode/DerivedData/flixr-snapshot")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
concurrent_simulators(false)
