devices([
  "iPhone 17 Pro Max",
  "iPhone 17",
])

languages(["en-GB"])

scheme("flixr")
test_target_name("flixrUITests")
xcargs("-skip-testing:flixrTests")
derived_data_path("~/Library/Developer/Xcode/DerivedData/flixr-snapshot")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
stop_after_first_error(true)
